version: '2'
services:
  fluentd:
    image: fluent/fluentd
    volumes:
      - ./fluentd/etc:/fluentd/etc
    ports:
      - "24224:24224"
    expose:
      - "24224"
    networks:
      - trial-net
  app:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: fluentd
      options:
        tag: "nginx.{{.Name}}"
    networks:
      - trial-net
    depends_on:
      - fluentd
networks:
  trial-net:
    external: true
